dist: xenial
sudo: required
branches:
  only:
  - master
  - "/^release-.*$/"
before_install:
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --name xbuilder --use
before_script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
script:
  - ./build.sh $TRAVIS_BUILD_NUMBER
notifications:
  email: true
  on_success: always
  on_failure: change
after_success:
  - echo "All done!"
