services:
  - docker
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
install: true
before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - cat /etc/default/docker
  - docker version
script:
  - ./build.sh $TRAVIS_BUILD_NUMBER
notifications:
  email: true
  on_success: always
  on_failure: change
after_success:
  - echo "All done!"
