services:
  - docker
install: true
before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker version
script:
  - ./build.sh $TRAVIS_BUILD_NUMBER
notifications:
  email: true
  on_success: always
  on_failure: change
after_success:
  - echo "All done!"
