dist: xenial
sudo: required
branches:
  only:
  - master
  - "/.*/"
before_script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
script:
  - ./build.sh $TRAVIS_BUILD_NUMBER
notifications:
  email: true
after_success:
  - echo "All done!"
