---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yml
- service.yml

images:
- name: bamboo
  newName: docker.io/saidsef/ubuntu-bamboo-dockerfile
  newTag: latest
