---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bamboo
  labels:
    name: bamboo
    app: bamboo
spec:
  serviceName: "bamboo"
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: bamboo
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4567"
      labels:
        name: bamboo
        app: bamboo
    spec:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsGroup: 65534
        runAsUser: 65534
      containers:
        - image: docker.io/saidsef/atlassian-bamboo-cicd:v2023.04
          imagePullPolicy: Always
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          name: bamboo
          ports:
            - protocol: TCP
              containerPort: 8085
              name: bamboo
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
              ephemeral-storage: 3Gi
          livenessProbe:
            exec:
              command:
                - pgrep
                - java
            initialDelaySeconds: 10
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            tcpSocket:
              port: bamboo
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: data
            - name: data
              mountPath: /opt/atlassian-bamboo/logs
              subPath: logs
            - name: data
              mountPath: /opt/atlassian-bamboo/work
              subPath: work
            - name: data
              mountPath: /opt/atlassian-bamboo/conf/Catalina
              subPath: catalina
      volumes:
        - name: data
          emptyDir:
            sizeLimit: 3Gi
